name: super_editor_unofficial_helper
description: A package that adds some helpers for super_editor
version: 0.0.1

repository: https://github.com/SeanfvdM/super_editor_unofficial_helper

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  super_editor: ^0.2.2
  super_editor_markdown: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
